// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Scanflow.Xamarin.Native.iOS
{
	public partial class SettingsViewController : UIViewController
	{
        public bool AutoFlash = false;
        public SettingsViewController (IntPtr handle) : base (handle)
		{

		}
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            AutoFlash =! AutoFlash;
            enableAutoFlashLight.SetImage(UIImage.FromBundle("CheckBoxFill"),UIControlState.Normal);

        }
        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            NavigationController.NavigationBarHidden = true;
        }

        partial void applyBtnTapped(Foundation.NSObject sender)
		{
            NavigationController.DismissViewController(true,null);
        }
        partial void cancelBtnTapped(Foundation.NSObject sender)
		{
            NavigationController.DismissViewController(true, null);
        }
        partial void closeBtnTapped(Foundation.NSObject sender)
		{
            NavigationController.DismissViewController(true, null);
        }
    }
}
