// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Scanflow.Xamarin.Native.iOS
{
	public partial class SettingsTableViewCell : UITableViewCell
	{
		public SettingsTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
