#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Scanflow.Xamarin.Resource", IsApplication=true)]

namespace Scanflow.Xamarin
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F010000
			public const int check_animation = 2130771968;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int civAutoScanEnable = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int civGuideLineColor = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int civGuideLineWidth = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int civLineColor = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int civLineWidth = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int civMagnifierCrossColor = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int civMaskAlpha = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int civPointColor = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int civPointFillAlpha = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int civPointFillColor = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int civPointWidth = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int civShowEdgeMidPoint = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int civShowGuideLine = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int civShowMagnifier = 2130837517;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int black = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int black_444 = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int black_alpha50 = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int cherry_red = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int colorAccent = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int colorPrimary = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int colorPrimaryDark = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int gray = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int icActive = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int icFocused = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int icPressed = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int ic_launcher_background = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int logo_bottom_left = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int logo_bottom_right = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int logo_top_left = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int logo_top_right = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int primary = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int primaryDark = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int primary_20 = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int purple_200 = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int purple_500 = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int purple_700 = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int selector_button_text = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int selector_ic = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int settings_heading_color = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int teal_200 = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int teal_700 = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int tint_img_doc = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int txt_color = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int viewBgLineColor = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int viewBgLineColor_alpha30 = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int view_id_card_color = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int white = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int white_alpha50 = 2130903073;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int doneSize = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int margin_large = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int margin_medium = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int margin_small = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int margin_xlarge = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int margin_xsmall = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int rect_button_height = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int rect_button_margin = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int rect_button_width = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int round_button_large = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int round_button_medium = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int round_button_small = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int shutter_button_margin = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int spacing_large = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int spacing_medium = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int spacing_small = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int stroke_large = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int stroke_medium = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int stroke_small = 2130968594;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int animated_check = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int any = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int barcode = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int batch = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int bg_bottomsheet_with_line = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int bg_button_round_corners = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int bg_button_round_corners_without_fillcolors = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int bg_circle = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int bg_homescreen_blur = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int border_background = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int button_round_corners = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int check_mark = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int count_badge_circle = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int home_card_bg = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int ic_add_page = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int ic_any_scan = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int ic_back = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int ic_back_icon = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int ic_barcode = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int ic_baseline_navigate_next = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int ic_batch_scan = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int ic_close = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int ic_container_scan = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int ic_copy_text = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int ic_delete = 2131034136;
			
			// aapt resource value: 0x7F05001C
			public const int ic_document_more = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int ic_document_reorder = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int ic_document_scanning = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int ic_document_share = 2131034143;
			
			// aapt resource value: 0x7F050019
			public const int ic_doc_camera = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int ic_doc_gallery = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int ic_doc_multipages = 2131034139;
			
			// aapt resource value: 0x7F050020
			public const int ic_download = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int ic_flash_disable = 2131034145;
			
			// aapt resource value: 0x7F050022
			public const int ic_flash_enable = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int ic_flash_off = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int ic_flash_on = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int ic_flash_selector = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int ic_frame_scan_document = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int ic_frame_scan_rectangle = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int ic_frame_scan_square = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int ic_idcard_scan = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int ic_launcher_background = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int ic_launcher_foreground = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int ic_logo_scanflow = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int ic_one_of_many_codes = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int ic_one_touch_zoom = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public const int ic_outer_circle = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int ic_photo = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int ic_pivot_view = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int ic_pivot_view_center_line = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int ic_qrcode = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int ic_scanner_empty = 2131034164;
			
			// aapt resource value: 0x7F050035
			public const int ic_settings = 2131034165;
			
			// aapt resource value: 0x7F050036
			public const int ic_settings_white = 2131034166;
			
			// aapt resource value: 0x7F050037
			public const int ic_share = 2131034167;
			
			// aapt resource value: 0x7F050038
			public const int ic_shutter = 2131034168;
			
			// aapt resource value: 0x7F050039
			public const int ic_shutter_focused = 2131034169;
			
			// aapt resource value: 0x7F05003A
			public const int ic_shutter_normal = 2131034170;
			
			// aapt resource value: 0x7F05003B
			public const int ic_shutter_pressed = 2131034171;
			
			// aapt resource value: 0x7F05003C
			public const int ic_shutter_selected = 2131034172;
			
			// aapt resource value: 0x7F05003D
			public const int ic_splash = 2131034173;
			
			// aapt resource value: 0x7F05003E
			public const int ic_splash_icon = 2131034174;
			
			// aapt resource value: 0x7F05003F
			public const int ic_switch = 2131034175;
			
			// aapt resource value: 0x7F050040
			public const int ic_tyre_scan = 2131034176;
			
			// aapt resource value: 0x7F050041
			public const int ic_upload = 2131034177;
			
			// aapt resource value: 0x7F050042
			public const int image_1 = 2131034178;
			
			// aapt resource value: 0x7F050043
			public const int image_2 = 2131034179;
			
			// aapt resource value: 0x7F050044
			public const int image_3 = 2131034180;
			
			// aapt resource value: 0x7F050045
			public const int image_4 = 2131034181;
			
			// aapt resource value: 0x7F050046
			public const int onboardImage1a = 2131034182;
			
			// aapt resource value: 0x7F050047
			public const int onboardimageb = 2131034183;
			
			// aapt resource value: 0x7F050048
			public const int onboardimagec = 2131034184;
			
			// aapt resource value: 0x7F050049
			public const int onboardimaged = 2131034185;
			
			// aapt resource value: 0x7F05004A
			public const int qr_code = 2131034186;
			
			// aapt resource value: 0x7F05004B
			public const int screen_1_skip = 2131034187;
			
			// aapt resource value: 0x7F05004C
			public const int screen_2_skip = 2131034188;
			
			// aapt resource value: 0x7F05004D
			public const int screen_3_skip = 2131034189;
			
			// aapt resource value: 0x7F05004E
			public const int screen_4_skip = 2131034190;
			
			// aapt resource value: 0x7F05004F
			public const int search_page_svgrepo_com = 2131034191;
			
			// aapt resource value: 0x7F050050
			public const int settings = 2131034192;
			
			// aapt resource value: 0x7F050051
			public const int skip1 = 2131034193;
			
			// aapt resource value: 0x7F050052
			public const int skip2 = 2131034194;
			
			// aapt resource value: 0x7F050053
			public const int skip3 = 2131034195;
			
			// aapt resource value: 0x7F050054
			public const int skip4 = 2131034196;
			
			// aapt resource value: 0x7F050055
			public const int toplogo = 2131034197;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Font
		{
			
			// aapt resource value: 0x7F060000
			public const int appfont_regular = 2131099648;
			
			static Font()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Font()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070001
			public const int bottomSheet = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int btnApply = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int btnCancel = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int btnImageCapture = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int cbAutoExposure = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int cbAutoFlashLight = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int frame = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int homelogo = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int imageView = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int ivBack = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int ivClose = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int ivCopyResult = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int ivFlashLight = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int ivImage = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int ivSettings = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int logo = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int rb4k = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int rbAutoZoom = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int rbFullHd1080P = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int rbHd720P = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int rbOneTouchZoom = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int rbSd480P = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int rbZoomNone = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int recyclerView = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int rgResolutionOptions = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int rgZoomOptions = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int scanflowView = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int scrollView = 2131165212;
			
			// aapt resource value: 0x7F070000
			public const int SelectedItem = 2131165184;
			
			// aapt resource value: 0x7F07001D
			public const int skip = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int textView = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int textView2 = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int tvHeadingSettings = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int tvResult = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int tvTitleSelectResolution = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int tvTitleZoomOption = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int viewPager = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int viewTopLine = 2131165221;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080005
			public const int activity_main = 2131230725;
			
			// aapt resource value: 0x7F080000
			public const int BarcodeScanLayout = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int Homelayout = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int ScannersLayout = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int SettingsLayout = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int TextScanLayout = 2131230724;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F090000
			public const int ic_launcher = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int ic_launcher_foreground = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int ic_launcher_round = 2131296258;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0000
			public const int app_name = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int auto = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int back_button_alt = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int black_and_white = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int btn_capture = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int btn_scan = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int btn_scaned = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int btn_scanning = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int capture_button_alt = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int capture_mode_camera = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int capture_mode_hdr = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public const int capture_mode_night = 2131361803;
			
			// aapt resource value: 0x7F0A000C
			public const int delete_all_images = 2131361804;
			
			// aapt resource value: 0x7F0A000D
			public const int delete_button_alt = 2131361805;
			
			// aapt resource value: 0x7F0A000E
			public const int delete_dialog = 2131361806;
			
			// aapt resource value: 0x7F0A000F
			public const int delete_title = 2131361807;
			
			// aapt resource value: 0x7F0A0010
			public const int deletus = 2131361808;
			
			// aapt resource value: 0x7F0A0011
			public const int discard_all_images = 2131361809;
			
			// aapt resource value: 0x7F0A0012
			public const int document = 2131361810;
			
			// aapt resource value: 0x7F0A0016
			public const int error = 2131361814;
			
			// aapt resource value: 0x7F0A0013
			public const int err_camera_permission_required = 2131361811;
			
			// aapt resource value: 0x7F0A0014
			public const int err_scan_failed = 2131361812;
			
			// aapt resource value: 0x7F0A0015
			public const int err_scan_failed_container = 2131361813;
			
			// aapt resource value: 0x7F0A0017
			public const int format_x_no_of_scan = 2131361815;
			
			// aapt resource value: 0x7F0A0018
			public const int gallery_button_alt = 2131361816;
			
			// aapt resource value: 0x7F0A0019
			public const int no = 2131361817;
			
			// aapt resource value: 0x7F0A001B
			public const int normal = 2131361819;
			
			// aapt resource value: 0x7F0A001A
			public const int no_pdf_documents = 2131361818;
			
			// aapt resource value: 0x7F0A001C
			public const int preference_file_key = 2131361820;
			
			// aapt resource value: 0x7F0A001F
			public const int saved = 2131361823;
			
			// aapt resource value: 0x7F0A001D
			public const int save_pdf = 2131361821;
			
			// aapt resource value: 0x7F0A001E
			public const int save_to = 2131361822;
			
			// aapt resource value: 0x7F0A0020
			public const int scan = 2131361824;
			
			// aapt resource value: 0x7F0A0021
			public const int share = 2131361825;
			
			// aapt resource value: 0x7F0A0022
			public const int share_button_alt = 2131361826;
			
			// aapt resource value: 0x7F0A0023
			public const int share_hint = 2131361827;
			
			// aapt resource value: 0x7F0A0024
			public const int switch_camera_button_alt = 2131361828;
			
			// aapt resource value: 0x7F0A0026
			public const int today = 2131361830;
			
			// aapt resource value: 0x7F0A0027
			public const int todo = 2131361831;
			
			// aapt resource value: 0x7F0A0025
			public const int to_delete_pdf = 2131361829;
			
			// aapt resource value: 0x7F0A0028
			public const int txt_4k = 2131361832;
			
			// aapt resource value: 0x7F0A0029
			public const int txt_any = 2131361833;
			
			// aapt resource value: 0x7F0A002A
			public const int txt_any_scan = 2131361834;
			
			// aapt resource value: 0x7F0A002B
			public const int txt_apply = 2131361835;
			
			// aapt resource value: 0x7F0A002C
			public const int txt_authority_india = 2131361836;
			
			// aapt resource value: 0x7F0A002E
			public const int txt_barcode = 2131361838;
			
			// aapt resource value: 0x7F0A002D
			public const int txt_bar_code_scan = 2131361837;
			
			// aapt resource value: 0x7F0A002F
			public const int txt_batch_inventory = 2131361839;
			
			// aapt resource value: 0x7F0A0030
			public const int txt_batch_scan = 2131361840;
			
			// aapt resource value: 0x7F0A0031
			public const int txt_cancel = 2131361841;
			
			// aapt resource value: 0x7F0A0032
			public const int txt_container_scan = 2131361842;
			
			// aapt resource value: 0x7F0A0033
			public const int txt_container_scanning = 2131361843;
			
			// aapt resource value: 0x7F0A0034
			public const int txt_copy = 2131361844;
			
			// aapt resource value: 0x7F0A0035
			public const int txt_document_scanning = 2131361845;
			
			// aapt resource value: 0x7F0A0036
			public const int txt_enable_auto_exposure = 2131361846;
			
			// aapt resource value: 0x7F0A0037
			public const int txt_enable_auto_flashlight = 2131361847;
			
			// aapt resource value: 0x7F0A0038
			public const int txt_enable_auto_zoom = 2131361848;
			
			// aapt resource value: 0x7F0A0039
			public const int txt_enable_one_touch_zoom = 2131361849;
			
			// aapt resource value: 0x7F0A003A
			public const int txt_finish = 2131361850;
			
			// aapt resource value: 0x7F0A003B
			public const int txt_full_hd_1080p = 2131361851;
			
			// aapt resource value: 0x7F0A003C
			public const int txt_hcontainer_scanning = 2131361852;
			
			// aapt resource value: 0x7F0A003D
			public const int txt_hd_720p = 2131361853;
			
			// aapt resource value: 0x7F0A003E
			public const int txt_heading_authority = 2131361854;
			
			// aapt resource value: 0x7F0A003F
			public const int txt_heading_dob = 2131361855;
			
			// aapt resource value: 0x7F0A0040
			public const int txt_heading_document_number = 2131361856;
			
			// aapt resource value: 0x7F0A0041
			public const int txt_heading_father_name = 2131361857;
			
			// aapt resource value: 0x7F0A0042
			public const int txt_heading_fullname = 2131361858;
			
			// aapt resource value: 0x7F0A0043
			public const int txt_heading_identity_scanner = 2131361859;
			
			// aapt resource value: 0x7F0A0044
			public const int txt_heading_images = 2131361860;
			
			// aapt resource value: 0x7F0A0045
			public const int txt_heading_select_scanner = 2131361861;
			
			// aapt resource value: 0x7F0A0046
			public const int txt_home_desc = 2131361862;
			
			// aapt resource value: 0x7F0A0047
			public const int txt_id_card = 2131361863;
			
			// aapt resource value: 0x7F0A0048
			public const int txt_id_details = 2131361864;
			
			// aapt resource value: 0x7F0A0049
			public const int txt_id_scan = 2131361865;
			
			// aapt resource value: 0x7F0A004A
			public const int txt_none = 2131361866;
			
			// aapt resource value: 0x7F0A004B
			public const int txt_onboarding_screen_1 = 2131361867;
			
			// aapt resource value: 0x7F0A004C
			public const int txt_onboarding_screen_2 = 2131361868;
			
			// aapt resource value: 0x7F0A004D
			public const int txt_onboarding_screen_3 = 2131361869;
			
			// aapt resource value: 0x7F0A004E
			public const int txt_onboarding_screen_4 = 2131361870;
			
			// aapt resource value: 0x7F0A0050
			public const int txt_one_of_many_codes = 2131361872;
			
			// aapt resource value: 0x7F0A004F
			public const int txt_one_of_many_code_scan = 2131361871;
			
			// aapt resource value: 0x7F0A0051
			public const int txt_permission_not_accepted = 2131361873;
			
			// aapt resource value: 0x7F0A0052
			public const int txt_pivot_view = 2131361874;
			
			// aapt resource value: 0x7F0A0053
			public const int txt_pivot_view_scan = 2131361875;
			
			// aapt resource value: 0x7F0A0054
			public const int txt_qr_code = 2131361876;
			
			// aapt resource value: 0x7F0A0055
			public const int txt_qr_scan = 2131361877;
			
			// aapt resource value: 0x7F0A0056
			public const int txt_result_qr_code = 2131361878;
			
			// aapt resource value: 0x7F0A0057
			public const int txt_scan_more = 2131361879;
			
			// aapt resource value: 0x7F0A0058
			public const int txt_scan_the_back_side_of_document = 2131361880;
			
			// aapt resource value: 0x7F0A0059
			public const int txt_scan_the_front_side_of_document = 2131361881;
			
			// aapt resource value: 0x7F0A005A
			public const int txt_sd_480p = 2131361882;
			
			// aapt resource value: 0x7F0A005B
			public const int txt_see_details = 2131361883;
			
			// aapt resource value: 0x7F0A005C
			public const int txt_select_resolution = 2131361884;
			
			// aapt resource value: 0x7F0A005D
			public const int txt_settings = 2131361885;
			
			// aapt resource value: 0x7F0A005E
			public const int txt_skip = 2131361886;
			
			// aapt resource value: 0x7F0A005F
			public const int txt_tyre_scan = 2131361887;
			
			// aapt resource value: 0x7F0A0060
			public const int txt_tyre_scanning = 2131361888;
			
			// aapt resource value: 0x7F0A0061
			public const int txt_vcontainer_scanning = 2131361889;
			
			// aapt resource value: 0x7F0A0062
			public const int txt_zoom_option = 2131361890;
			
			// aapt resource value: 0x7F0A0063
			public const int yes = 2131361891;
			
			// aapt resource value: 0x7F0A0064
			public const int yesterday = 2131361892;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public const int AppTheme = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int BottomSheetCustom = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int BottomSheetCustom_BottomSheetStyle = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int BottomSheetCustom_DialogTheme = 2131427331;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F020000,0x7F020001,0x7F020002,0x7F020003,0x7F020004,0x7F020005,0x7F020006,0x7F020007,0x7F020008,0x7F020009,0x7F02000A,0x7F02000B,0x7F02000C,0x7F02000D }
			public static int[] CropImageView = new int[] {
					2130837504,
					2130837505,
					2130837506,
					2130837507,
					2130837508,
					2130837509,
					2130837510,
					2130837511,
					2130837512,
					2130837513,
					2130837514,
					2130837515,
					2130837516,
					2130837517};
			
			// aapt resource value: 0
			public const int CropImageView_civAutoScanEnable = 0;
			
			// aapt resource value: 1
			public const int CropImageView_civGuideLineColor = 1;
			
			// aapt resource value: 2
			public const int CropImageView_civGuideLineWidth = 2;
			
			// aapt resource value: 3
			public const int CropImageView_civLineColor = 3;
			
			// aapt resource value: 4
			public const int CropImageView_civLineWidth = 4;
			
			// aapt resource value: 5
			public const int CropImageView_civMagnifierCrossColor = 5;
			
			// aapt resource value: 6
			public const int CropImageView_civMaskAlpha = 6;
			
			// aapt resource value: 7
			public const int CropImageView_civPointColor = 7;
			
			// aapt resource value: 8
			public const int CropImageView_civPointFillAlpha = 8;
			
			// aapt resource value: 9
			public const int CropImageView_civPointFillColor = 9;
			
			// aapt resource value: 10
			public const int CropImageView_civPointWidth = 10;
			
			// aapt resource value: 11
			public const int CropImageView_civShowEdgeMidPoint = 11;
			
			// aapt resource value: 12
			public const int CropImageView_civShowGuideLine = 12;
			
			// aapt resource value: 13
			public const int CropImageView_civShowMagnifier = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
